<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Factor a_b</name>
   <tag></tag>
   <elementGuidId>1b13d915-b577-46a0-b757-72f9e1ef5470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07c99eeb-b085-4817-b58e-50a93ad687be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>033c7b7b-bac6-4d4b-8733-782f00328866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>9e51ba85-6340-4e12-9b89-52bf1505cdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b&quot;)</value>
      <webElementGuid>e873e243-21bd-43df-a8c9-516706263bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b']</value>
      <webElementGuid>6a145b0b-1cb1-4447-b8bf-20d10e9cb195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>d1769512-730e-43dd-a3b9-368825f0cab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b']</value>
      <webElementGuid>2a270257-9f7e-4bd9-9231-7595e43a07b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
