<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Factor a_a</name>
   <tag></tag>
   <elementGuidId>aa8e6918-5570-44bd-8409-bbeaa7e9f5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae7cd367-32fd-4c49-a4fb-76dd7d561b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7490bb8a-805d-43ca-8ebc-c82fc18f6500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f85b69f7-fb00-4ca5-ac4e-5d64398f347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a&quot;)</value>
      <webElementGuid>932fa2a0-4c24-42a4-a110-b4de41b106a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a']</value>
      <webElementGuid>5601e4ce-2c3d-455a-92b8-16c76f612ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>18df9b30-f82a-4346-8d9e-17a2526791ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'a']</value>
      <webElementGuid>6daac1de-454c-402e-b501-1e1f08bad912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
