<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_x  0</name>
   <tag></tag>
   <elementGuidId>1e27f53b-94f6-439f-ad03-bc71b352244c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='e1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd83efbc-7421-4b12-a158-96e18ef791be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e1</value>
      <webElementGuid>e5453a40-1bc8-4da3-a605-db4603517c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x = 0</value>
      <webElementGuid>5705315a-9108-490f-a06f-700b2eb960c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e1&quot;)</value>
      <webElementGuid>1da6c76e-d2fc-4f77-8272-ab6907fd0b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e1']</value>
      <webElementGuid>0c24a0eb-272f-4695-bc38-0ebc8882e332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'e1', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>3b821810-2549-45ca-9e49-fe5b78000201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x = 0']/parent::*</value>
      <webElementGuid>18ba962a-ac7c-483d-ad43-b30871d3023b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>0e0e293b-e1b1-479b-9746-b3e0db65d0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e1' and (text() = 'x = 0' or . = 'x = 0')]</value>
      <webElementGuid>c92c7de6-ece3-40dc-b03b-d04215bd4ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
