<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_x  -2</name>
   <tag></tag>
   <elementGuidId>92555338-bba1-4c91-babd-a2c83ebffd38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='e1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>acfbff35-46f3-49a7-8d69-7a15a769181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e1</value>
      <webElementGuid>4b361d3b-4670-4d40-b586-eecd5f27c79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x = -2</value>
      <webElementGuid>4c437e97-bc8b-4ce3-b78f-4293816e2223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e1&quot;)</value>
      <webElementGuid>d018f1aa-847d-4854-9922-cc3a3c5e5709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e1']</value>
      <webElementGuid>ec2367d5-76eb-4bc3-b2b9-5655febd0fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'e1', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>8e7b6f18-ba87-4ea1-b181-ac7778dad869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x = -2']/parent::*</value>
      <webElementGuid>cfe8b176-921b-4373-933a-4de95d2d592f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>2148cf5f-a464-4275-9206-6c77d053d49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e1' and (text() = 'x = -2' or . = 'x = -2')]</value>
      <webElementGuid>e85e8186-824b-465f-adc5-911fa7951eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
