<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_No solution</name>
   <tag></tag>
   <elementGuidId>85f08b60-3d01-4e93-b477-1d6afc40dec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='e1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0208541-2a49-4ff4-a26d-29b3d2a86504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e1</value>
      <webElementGuid>635f28b4-214b-4f47-91b9-fb83efbde505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No solution</value>
      <webElementGuid>7793eced-6cda-4205-8f30-1ffb783d0e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e1&quot;)</value>
      <webElementGuid>d1fd778c-8f34-4fea-9500-7ddc46b27d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e1']</value>
      <webElementGuid>660a977c-f461-4b64-920f-aaf36325ef71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'e1', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>481e7843-a962-4fef-a800-872ac63a17fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No solution']/parent::*</value>
      <webElementGuid>5c7a5a22-c0a2-4f94-a962-bcb49402542a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>d248af48-19a4-447c-af13-f470a21464f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e1' and (text() = 'No solution' or . = 'No solution')]</value>
      <webElementGuid>939a26f6-3d54-4873-b860-ba404c041f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
